# goals:
#   - name: Potato_disease_detection_pose
#     x: 0.5
#     y: 0.0
#     yaw: 0.0
#   - name: point1
#     x: -0.5
#     y: -0.5
#     yaw: -1.57
#   - name: ramp1
#     x: 0.2
#     y: -1.5
#     yaw: 0.0 
#   - name: point2
#     x: 1.4
#     y: -2.0
#     yaw: 0.0
#   - name: point3
#     x: 1.3
#     y: -1.0
#     yaw: -1.57
#   - name: Loading_zone
#     x: 0.2
#     y: -1.3
#     yaw: 0.0
#   - name: point4
#     x: 1.2
#     y: 0.0
#     yaw: 0.0
#   - name: point5
#     x: 2.5
#     y: 0.2
#     yaw: 0.0
#   - name: point6
#     x: 4.5
#     y: 0.2
#     yaw: 0.0
#   - name: point7
#     x: 4.5
#     y: -1.0
#     yaw: 0.0
#   - name: point8
#     x: 2.0
#     y: -1.0
#     yaw: 0.0
#   - name: Offloading_blue
#     x: 2.0
#     y: -2.0
#     yaw: 0.0
#   - name: point9
#     x: 2.3
#     y: -1.7
#     yaw: 0.0
#   - name: Offloading_red
#     x: 2.7
#     y: -2.0
#     yaw: 0.0
#   - name: final_position
#     x: 4.5
#     y: -1.7
#     yaw: 3.14

#r3
goals:
  - name: Potato_disease_detection_pose
    x: 0.37
    y: -0.63
    yaw: 0.0
  - name: point1
    x: -0.7
    y: -0.5
    yaw: -1.57
  - name: ramp1
    x: -0.7
    y: -0.9
    yaw: -1.57 
  - name: point2
    x: -0.5
    y: -2.7
    yaw: 0.0
  # - name: point3
  #   x: 1.3
  #   y: -2.7
  #   yaw: 1.57
  - name: point4
    x: 1.3
    y: -1.5
    yaw: 3.14
  - name: Loading_zone
    x: 0.26
    y: -1.7
    yaw: 0.0
  # - name: point5
  #   x: 1.3
  #   y: -0.3
  #   yaw: 0.0
  - name: point6
    x: 2.5
    y: -0.3
    yaw: 0.0
  - name: point7
    x: 4.5
    y: -0.5
    yaw: -1.57
  # - name: point8
  #   x: 4.5
  #   y: -1.5
  #   yaw: 3.14
  - name: point9
    x: 2.0
    y: -1.5
    yaw: -1.17
  - name: Offloading_blue
    x: 2.1
    y: -2.6
    yaw: 1.68
  - name: point10
    x: 2.6    
    y: -2.14
    yaw: 0.0
  - name: Offloading_red
    x: 2.8
    y: -2.5
    yaw: 1.68
  - name: final_position
    x: 4.5
    y: -2.5
    yaw: 3.14

# goals:
#     - name: loading_zone
#       x: -2.0
#       y: 1.1
#       yaw: 0.0
#     - name: potato_disease_detection_pose
#       x: -2.0
#       y: 0.0
#       yaw: 3.14
#     - name: offloading_blue
#       x: -0.5
#       y: 1.5
#       yaw: 0.0  
#     - name: offloading_red
#       x: -1.5
#       y: 1.5
#       yaw: 0.0
#     - name: final_position
#       x: -1.0
#       y: 1.0
#       yaw: 3.14

# goals:
#     - name: potato_disease_detection_pose
#       x: 0.2
#       y: 0.3
#       yaw: 0.0
#     - name: loading_zone
#       x: 1.0
#       y: 0.2
#       yaw: 0.0
#     - name: offloading_blue
#       x: 1.0
#       y: 0.2
#       yaw: 0.0  
#     - name: offloading_red
#       x: 0.8
#       y: -1.0
#       yaw: 0.0
#     - name: final_position
#       x: 1.5
#       y: -1.3
#       yaw: 3.14 