goals:
  - name: point1
    x: -0.5
    y: -2.1
    yaw: -1.57
  - name: point2
    x: 1.3
    y: -2.0
    yaw: 0.0
  - name: point3
    x: 1.2
    y: 0.0
    yaw: -1.57
  - name: point4
    x: 2.5
    y: 0.2
    yaw: 0.0
  - name: point5
    x: 4.5
    y: 0.2
    yaw: 0.0
  - name: point6
    x: 4.5
    y: -1.0
    yaw: 0.0
  - name: point7
    x: 2.0
    y: -1.0
    yaw: 0.0
  - name: point8
    x: 2.0
    y: -1.7
    yaw: 0.0
  - name: point9
    x: 4.0
    y: -1.7
    yaw: 0.0
