<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.290"/>
    <xacro:property name="chassis_width" value="0.170"/>
    <xacro:property name="chassis_height" value="0.036"/>

    <xacro:property name="head_length" value="${chassis_length/2}"/>
    <xacro:property name="head_width" value="${chassis_width*1.4}"/>
    <xacro:property name="head_height" value="0.0448"/>

    <xacro:property name="chassis_mass" value="1.0"/>

    <xacro:property name="wheel_radius" value="0.0425"/>
    <xacro:property name="wheel_thickness" value="0.038"/>
    <xacro:property name="wheel_mass" value="0.05"/>

    <xacro:property name="front_wheel_offset_x" value="0.2148"/>
    <xacro:property name="front_wheel_offset_y" value="${0.1024}"/>
    <!-- <xacro:property name="front_wheel_offset_z" value="0.01"/> -->
     <xacro:property name="front_wheel_offset_z" value="${wheel_radius}"/>

    <xacro:property name="back_wheel_offset_x" value="0.0748"/>
    <xacro:property name="back_wheel_offset_y" value="${front_wheel_offset_y}"/>
    <xacro:property name="back_wheel_offset_z" value="${front_wheel_offset_z}"/>

    <xacro:property name="lidar_height" value="0.023"/>
    <xacro:property name="lidar_offset_x" value="0.224"/>
    <xacro:property name="lidar_offset_z" value="${chassis_height + head_height + front_wheel_offset_z}"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-back_wheel_offset_x} 0 ${-front_wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2 + front_wheel_offset_z}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2  + front_wheel_offset_z}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2  + front_wheel_offset_z}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>


    <joint name="head_joint" type="fixed">
        <parent link="chassis"/>
        <child link="head"/>
        <origin xyz="${chassis_length - head_length/2} 0 ${head_height/2 + front_wheel_offset_z}"/>
    </joint>

    <link name="head">
        <visual>
            <origin xyz="0 0 ${head_height}"/>
            <geometry>
                <box size="${head_length} ${head_width} ${head_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${head_height}"/>
            <geometry>
                <box size="${head_length} ${head_width} ${head_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${head_length}" y="${head_width}" z="${head_height}">
            <origin xyz="0 0 ${head_height}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="head">
        <material>Gazebo/Black</material>
    </gazebo>



    <joint name="front_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left"/>
        <origin xyz="${front_wheel_offset_x - back_wheel_offset_x} ${front_wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_left">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_left">
        <material>Gazebo/Red</material>
    </gazebo>


    <joint name="front_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right"/>
        <origin xyz="${front_wheel_offset_x - back_wheel_offset_x} ${-front_wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="front_right">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_right">
        <material>Gazebo/Red</material>
    </gazebo>


    <joint name="back_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="back_left"/>
        <origin xyz="0 ${back_wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="back_left">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="back_left">
        <material>Gazebo/Blue</material>
    </gazebo>


    <joint name="back_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="back_right"/>
        <origin xyz="0 ${-back_wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="back_right">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="back_right">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="lidar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="${lidar_offset_x} 0 ${lidar_offset_z + 0.05}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="${lidar_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <visual>
            <origin xyz="0 0 -0.05"/>
            <geometry>
                <cylinder radius="0.01" length="0.1"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="${lidar_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <gazebo reference="laser_frame">
        <material>Gazebo/White</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>--ros-args --remap ~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>